//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomationWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int personal_id { get; set; }
        public string Personal_name { get; set; }
        public string Personal_lastname { get; set; }
        public string Personal_TC { get; set; }
        public string Personal_phone { get; set; }
        public string Personal_mail { get; set; }
        public string Personal_userName { get; set; }
        public string Personal_password { get; set; }
    }
}
