//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomationWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int record_id { get; set; }
        public Nullable<int> userr_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<bool> statuss { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
